defaults: &defaults
  per_page: 20
  per_page_api: 10
  per_page_modal: 10
  construction_info:
    promote_to_construction_probability: 5
    use_probability_ids:
      - 5
      - 6
      - 7
      - 8
      - 10

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
