source 'https://rubygems.org'


gem 'rails', '5.0.0'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

gem 'jquery-rails'
gem 'turbolinks', '~> 5.x'
gem 'jquery-turbolinks'
gem 'jbuilder', '~> 2.0'

gem 'devise'
gem 'omniauth'
gem 'omniauth-oauth2', '~> 1.3.1' # 1.4.0 bugで動かない
gem 'dotenv-rails'

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem 'slim-rails'
gem 'ransack'
gem 'kaminari'
gem 'settingslogic'
gem 'enum_help'
gem 'seed-fu'
gem 'activerecord-import'
gem 'active_decorator'
gem 'active_decorator_with_decorate_associations'
gem 'virtus'
gem 'autonumeric-rails'
gem 'faraday'
gem 'nested_form'
gem 'paranoia', github: 'rubysherpas/paranoia', branch: 'rails5'
gem 'paranoia_uniqueness_validator', '2.0.0'
gem 'gon'

# Css Framework
gem 'bulma-rails', '~> 0.0.28'
gem 'font-awesome-rails'

gem 'json_report_builder', git: 'git@developer.luxiar.jp:luxiar/json_report_builder.git'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'rails-controller-testing', git: 'https://github.com/rails/rails-controller-testing'
  gem 'rspec-rails'
  gem 'shoulda-matchers', :require => false
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'forgery'
  gem 'rubocop'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'poltergeist'
  gem 'selenium-webdriver'
  gem 'turnip'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
