
STRIPE_SECRET_KEY: 'sk_test_WJWPxSsj07RtHMLa0Cm6ZIrO'
STRIPE_PUBLIC_KEY: 'pk_test_7UySrI7Uc62beTK6TOIhyvsF'

MAILER_API_KEY: 'snsn0803' #ENV['MAILER_API_KEY'] のように定数として使用できる

FACEBOOK_APP_ID: '312561132466456'
FACEBOOK_APP_SECRET: '4e32c5eeef907a7a65606a66fd908515'

GITHUB_APP_ID: 'dabe88cda37b5be7c2b4'
GITHUB_APP_SECRET: 'bcaa3ef4a7c2df92e23330721493a9d6a95c26aa'