# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f269779f510af249865896473503846ac125ebc8dc07617c50f48ac2c3d21bb3e3336bed6568a9db6dd75988dc776a05262b2f9d47fa9fe0395de1271c83091

test:
  secret_key_base: 60b12a8c76f7238e0cf144825e5eedf41912b9fdc39ebe25c309062ab2f590c2f4af59468a3ac9e98a0440a90e56a8dfdb89043c5e3e129b463d2a0a7c7777b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
